
# Font settings
font_family      Fira Code
font_size        12.0

# Cursor customization
cursor_shape     beam
cursor_blink_interval 0.5

# Window layout and appearance
background_opacity 0.6
window_padding_width 4
active_border_color #ffffff
background #0F1936

# Tab bar style
tab_bar_style powerline
tab_powerline_style slanted

# Keyboard shortcuts
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+enter new_window_with_cwd
