shell /usr/bin/zsh
# Font settings
font_family      Fira Code
font_size        12.0

# Cursor customization
cursor_shape     beam
cursor_blink_interval 0.5

# Window layout and appearance
background_opacity 0.75
window_padding_width 4
active_border_color #ffffff
background #0F1936

# Tab bar style
tab_bar_style powerline
tab_powerline_style slanted

# Keyboard shortcuts
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+enter new_window_with_cwd


cursor                #fffefe
selection_background  #003e8e
color0                #000000
color8                #000000
color1                #ff9ca3
color9                #ff9ca3
color2                #d0f0a8
color10               #d0f0a8
color3                #ffedac
color11               #ffedac
color4                #badaff
color12               #badaff
color5                #ebbaff
color13               #ebbaff
color6                #99ffff
color14               #99ffff
color7                #fffefe
color15               #fffefe
selection_foreground #002450
