splash = false

wallpaper {
	monitor = HDMI-A-1
	path = ~/Pictures/782148-9-16-crop.png
	fit_mode = cover:
}

wallpaper {
	monitor = DP-1
	path = ~/Pictures/782148.jpg
	fit_mode = cover:
}

wallpaper {
	monitor = DP-2
	path = ~/Pictures/782148.jpg
	fit_mode = cover:
}

wallpaper {
	monitor = DP-3
	path = ~/Pictures/782148.jpg
	fit_mode = cover:
}
