#Adrienne's hyprland config
#Some stuff like monitors is being handled by hyprmod's gui, i should see if i can transfer that over to the files

################
### MONITORS ###
################

source = ~/.config/hypr/sources/monitors.conf


###############
## AUTOSTART ##
###############

source = ~/.config/hypr/sources/autostart.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################

source = ~/.config/hypr/sources/envVAR.conf

###################
### PERMISSIONS ###
###################

source = ~/.config/hypr/sources/perms.conf

#####################
### LOOK AND FEEL ###
#####################

source = ~/.config/hypr/sources/looknfeel.conf


#############
### INPUT ###
#############

source = ~/.config/hypr/sources/input.conf

###################
### KEYBINDINGS ###
###################

source = ~/.config/hypr/sources/binds.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

source = ~/.config/hypr/sources/winrules.conf

# HyprMod managed settings
source = /home/lozplyr89/.config/hypr/hyprland-gui.conf
